export const FETCH_WEATHER_DATA_REQUEST = 'FETCH_WEATHER_DATA_REQUEST';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';
export const FETCH_FORECAST_DATA_REQUEST = 'FETCH_FORECAST_DATA_REQUEST';
export const FETCH_FORECAST_DATA_SUCCESS = 'FETCH_FORECAST_DATA_SUCCESS';
export const FETCH_FORECAST_DATA_FAIL = 'FETCH_FORECAST_DATA_FAIL';